# ChzzkMc 설정

# 치지직 채널 ID (스트리밍 링크 마지막 부분)
channel-id: "1dcb975316a0be7bc445beecc29b9673"

# 치지직 채팅 출력 여부
broadcast-chat: false

display:
  # 남은 시간 표시 방식 (action_bar 또는 chat)
  timer: "action_bar"

vote:
  # 투표 선택지 개수 (2-4)
  option: 3
  # 투표 선택지 제목
  titles:
    - "1번에 투표하세요!"
    - "2번에 투표하세요!"
    - "3번에 투표하세요!"
    - "4번에 투표하세요!"
  # 투표 지속 시간 (초)
  durationSec: 120
